### ISSUE TITLE
Update the Drawing Process to Use Registry

### ISSUE THREAD

**Issue by QriusDev** [GearTech0/QriusPlayer#7]
Right now, adding new Drawables requires some modifications of the MediaPlayer object. I don't like that since I want others to be able to build from this. Therefore, I believe adding a registry flow is the way to go.

Action Items:
- Gut MediaPlayer.Animate() and create a draw_registry variable to keep track of all Drawables that want to be drawn.
- In MediaPlayer.Animate(), run through the registry and just animate whatever is there. Deletion is also simpler here.

**Comment by dylta** [comment]
Resolved by da3ed56
